package __APP_ID__.core.extraction

/**
 * Engine-neutral models. Nothing in here may reference NewPipe, yt-dlp or any other
 * extraction library, so the engine can be replaced without touching UI, player,
 * downloads or the database.
 */

data class VideoSummary(
    val id: String,
    val title: String,
    val channel: String,
    val channelUrl: String?,
    val durationSeconds: Long,
    val thumbnailUrl: String?,
    val viewCount: Long,
    val uploadedText: String?,
    val isLive: Boolean,
)

data class VideoDetails(
    val summary: VideoSummary,
    val description: String,
    val ageLimit: Int,
)

enum class AudioTrackKind { ORIGINAL, DUBBED, DESCRIPTIVE, SECONDARY, UNKNOWN }

enum class Delivery { PROGRESSIVE, DASH, HLS, OTHER }

data class VideoStreamOption(
    val itag: Int,
    val width: Int,
    val height: Int,
    val fps: Int,
    val codec: String?,
    val container: String?,
    val bitrateKbps: Int,
    /** true = progressive stream that already contains audio (usually <= 720p). */
    val hasAudio: Boolean,
    val delivery: Delivery,
    val url: String,
)

data class AudioStreamOption(
    val itag: Int,
    /** Source-provided track identifier; null when the video has a single, unlabeled track. */
    val trackId: String?,
    val languageTag: String?,
    val trackName: String?,
    val kind: AudioTrackKind,
    val codec: String?,
    val container: String?,
    val bitrateKbps: Int,
    val delivery: Delivery,
    val url: String,
)

data class SubtitleOption(
    val languageTag: String,
    val autoGenerated: Boolean,
    /** File suffix such as "vtt", "ttml", "srt". */
    val format: String?,
    val url: String,
)

data class StreamSet(
    val video: List<VideoStreamOption>,
    val audio: List<AudioStreamOption>,
    val subtitles: List<SubtitleOption>,
    val hlsUrl: String?,
    val dashManifestUrl: String?,
)

/** Everything known about one video, from a single fetch. */
data class VideoInfo(
    val details: VideoDetails,
    val streams: StreamSet,
)

/** Opaque continuation handle for search paging. */
data class SearchCursor(val query: String, val raw: Any)

data class SearchPage(
    val results: List<VideoSummary>,
    val next: SearchCursor?,
)

data class EngineInfo(
    val name: String,
    val version: String,
    val notes: String,
)
