package __APP_ID__.core.extraction

/**
 * Plain-text description of what the extraction engine ACTUALLY returned for a video.
 * Used by the "Copy report" button so real-world results (multi-audio, dubs, subtitles,
 * qualities) can be recorded instead of assumed. Never includes stream URLs.
 */
object StreamReport {

    fun build(info: VideoInfo, engine: EngineInfo): String = buildString {
        val d = info.details
        val s = info.streams
        appendLine("DarkTube stream report")
        appendLine("Engine: ${engine.name} ${engine.version}")
        appendLine("Video id: ${d.summary.id}")
        appendLine("Title: ${d.summary.title}")
        appendLine("Channel: ${d.summary.channel}")
        appendLine("Duration: ${Formatters.duration(d.summary.durationSeconds)}  Live: ${if (d.summary.isLive) "yes" else "no"}")
        appendLine("Delivery: progressive=${count(s, Delivery.PROGRESSIVE)} dash=${count(s, Delivery.DASH)} hls=${count(s, Delivery.HLS)} other=${count(s, Delivery.OTHER)}")
        appendLine("Manifests: hls=${s.hlsUrl != null} dash=${s.dashManifestUrl != null}")
        appendLine()

        val qualities = StreamCatalog.qualities(s.video)
        appendLine("Video qualities (${qualities.size}):")
        if (qualities.isEmpty()) appendLine("  none")
        for (q in qualities) {
            val parts = q.candidates.joinToString("; ") {
                val kind = if (it.hasAudio) "muxed" else "video-only"
                "${StreamCatalog.codecFamily(it.codec)}/${it.container ?: "?"} ${Formatters.bitrate(it.bitrateKbps)} $kind itag=${it.itag}"
            }
            appendLine("  ${q.label}: $parts")
        }
        appendLine()

        val tracks = StreamCatalog.audioTracks(s.audio)
        appendLine("Audio tracks (${tracks.size}):")
        if (tracks.isEmpty()) appendLine("  none")
        for (t in tracks) {
            appendLine("  ${t.label}  [kind=${t.kind} lang=${t.languageTag ?: "-"} id=${t.trackId ?: "-"}]")
            for (a in t.streams) {
                appendLine("    ${a.codec ?: "?"}/${a.container ?: "?"} ${Formatters.bitrate(a.bitrateKbps)} itag=${a.itag} ${a.delivery}")
            }
        }
        appendLine()

        val subs = StreamCatalog.subtitleTracks(s.subtitles)
        appendLine("Subtitles (${subs.size}):")
        if (subs.isEmpty()) appendLine("  none")
        for (t in subs) {
            appendLine("  ${t.label}  [lang=${t.languageTag} ${if (t.autoGenerated) "auto" else "manual"}] formats=${t.formats.joinToString(",") { it.format ?: "?" }}")
        }
    }

    private fun count(s: StreamSet, d: Delivery) =
        s.video.count { it.delivery == d } + s.audio.count { it.delivery == d }
}
