package __APP_ID_PATH__.ui.downloads

import __APP_ID__.core.download.DownloadManager
import __APP_ID__.core.download.OutputFiles
import __APP_ID__.core.log.AppLog
import __APP_ID__.core.playback.PipState
import __APP_ID__.core.playback.PlayerConnection
import __APP_ID__.core.playback.PlayerSession
import __APP_ID__.core.playback.SubtitleSource
import __APP_ID__.core.playback.selectSubtitle
import __APP_ID__.core.playback.selectedSubtitleId
import __APP_ID__.data.db.DownloadEntity
import __APP_ID__.ui.video.DropdownRow
import __APP_ID__.ui.video.Muted
import __APP_ID__.ui.video.PlayerSurface
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.media3.common.PlaybackException
import androidx.media3.common.Player

/** Plays a finished download in the SAME Media3 player used for streaming (no second player). */
@Composable
fun LocalPlayerScreen(
    downloadId: Long,
    downloads: DownloadManager,
    playerConnection: PlayerConnection,
    pip: PipState,
    onBack: () -> Unit,
) {
    val entity by produceState<DownloadEntity?>(null, downloadId) { value = downloads.get(downloadId) }
    val controller by playerConnection.controller.collectAsStateWithLifecycle()
    var error by remember { mutableStateOf<String?>(null) }
    var selectedSub by remember { mutableStateOf<String?>(null) }
    var subNote by remember { mutableStateOf<String?>(null) }

    DisposableEffect(Unit) {
        onDispose {
            playerConnection.stopAndClear()
            pip.eligible = false
        }
    }

    val e = entity
    val subs = remember(e) {
        if (e == null) emptyList() else DownloadManager.subtitleFileUris(e).map { (lang, uri, name) ->
            val ext = name.substringAfterLast('.')
            SubtitleSource(
                id = "sub:$lang:local",
                label = lang,
                languageTag = lang,
                autoGenerated = false,
                mimeType = OutputFiles.mimeType(ext),
                url = uri,
            )
        }
    }

    LaunchedEffect(controller, e) {
        val c = controller ?: return@LaunchedEffect
        val d = e ?: return@LaunchedEffect
        val uri = d.destinationUri ?: return@LaunchedEffect
        error = null
        if (PlayerSession.loadLocal(c, "local:${d.id}", d.title, d.thumbnailUrl, uri, subs)) {
            AppLog.i("Player", "load local download #${d.id} subs=${subs.size}")
        }
    }

    DisposableEffect(controller) {
        val c = controller
        selectedSub = c?.selectedSubtitleId()
        val l = object : Player.Listener {
            override fun onPlayerError(err: PlaybackException) {
                AppLog.e("Player", "local playback error ${err.errorCodeName}")
                error = "This file could not be played. It may have been moved or deleted."
            }
            override fun onIsPlayingChanged(isPlaying: Boolean) { pip.eligible = isPlaying }
            override fun onTracksChanged(tracks: androidx.media3.common.Tracks) { selectedSub = c?.selectedSubtitleId() }
        }
        c?.addListener(l)
        onDispose { c?.removeListener(l) }
    }

    Column(Modifier.fillMaxSize()) {
        IconButton(onClick = onBack) { Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back") }
        PlayerSurface(controller, showControls = true, onFullscreen = {}, modifier = Modifier.fillMaxWidth().aspectRatio(16f / 9f))
        Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
            Text(e?.title ?: "", style = MaterialTheme.typography.titleLarge)
            if (e != null) Muted("${e.resolvedHeight?.let { "${it}p · " } ?: ""}${e.audioLabel} · ${e.destinationName ?: ""}")
            error?.let { Text(it, color = MaterialTheme.colorScheme.error) }
            if (subs.isNotEmpty()) {
                val current = subs.firstOrNull { it.id == selectedSub }?.label ?: "Off"
                DropdownRow("Subtitles", current, listOf<Pair<String?, String>>(null to "Off") + subs.map { it.id to it.label }) { id ->
                    val c = controller
                    if (c != null) {
                        if (!c.selectSubtitle(id)) subNote = "Subtitle tracks are still loading. Try again in a moment." else subNote = null
                    }
                }
                subNote?.let { Text(it, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.error) }
            }
        }
    }
}
