package __APP_ID__.core

import __APP_ID__.core.extraction.StreamCatalog
import __APP_ID__.core.extraction.SubtitleOption
import __APP_ID__.core.playback.SubtitlePlanner
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class SubtitlePlannerTest {
    private fun s(lang: String, auto: Boolean, fmt: String?) = SubtitleOption(lang, auto, fmt, "u-$lang-$auto-$fmt")
    private fun plan(vararg subs: SubtitleOption) = SubtitlePlanner.sources(StreamCatalog.subtitleTracks(subs.toList()))

    @Test fun mimeMapping() {
        assertEquals("application/ttml+xml", SubtitlePlanner.mimeFor("ttml"))
        assertEquals("text/vtt", SubtitlePlanner.mimeFor("VTT"))
        assertEquals("application/x-subrip", SubtitlePlanner.mimeFor("srt"))
        assertNull(SubtitlePlanner.mimeFor("srv3"))
        assertNull(SubtitlePlanner.mimeFor(null))
    }

    @Test fun manualAndAutoOfSameLanguageGetDifferentIdsAndKeepTheirType() {
        val out = plan(s("en", false, "ttml"), s("en", true, "ttml"))
        assertEquals(2, out.size)
        assertEquals(2, out.map { it.id }.toSet().size)
        assertFalse(out.first { !it.autoGenerated }.label.contains("auto"))
        assertTrue(out.first { it.autoGenerated }.label.contains("auto-generated"))
    }

    @Test fun vttPreferredWhenSeveralFormatsExist() {
        val out = plan(s("ar", false, "ttml"), s("ar", false, "vtt")).single()
        assertEquals("text/vtt", out.mimeType)
        assertEquals("u-ar-false-vtt", out.url)
    }

    @Test fun unrenderableFormatsAreNotOffered() {
        val out = plan(s("ar", false, "srv3"), s("fr", false, "ttml"))
        assertEquals(listOf("fr"), out.map { it.languageTag })
    }

    @Test fun trackFallsBackToRenderableFormat() {
        val out = plan(s("ar", false, "srv3"), s("ar", false, "ttml")).single()
        assertEquals("application/ttml+xml", out.mimeType)
    }

    @Test fun nothingInventedWhenNoSubtitles() {
        assertTrue(plan().isEmpty())
    }

    @Test fun idsAreStableAcrossCalls() {
        val a = plan(s("ar", false, "ttml"), s("en", true, "ttml")).map { it.id }
        val b = plan(s("en", true, "ttml"), s("ar", false, "ttml")).map { it.id }
        assertEquals(a.toSet(), b.toSet())
        assertTrue(a.contains("sub:ar:manual"))
        assertTrue(a.contains("sub:en:auto"))
    }
}
