package __APP_ID__.core.playback

import __APP_ID__.core.extraction.StreamCatalog
import java.util.Locale

/** One subtitle track the player can actually render, ready to be attached to a MediaItem. */
data class SubtitleSource(
    /** Stable id; becomes the track's Format.id inside the player so the UI can find it again. */
    val id: String,
    val label: String,
    val languageTag: String,
    val autoGenerated: Boolean,
    val mimeType: String,
    val url: String,
)

/** Pure logic (no Android): which discovered subtitle tracks can be rendered, and as what. */
object SubtitlePlanner {
    const val MIME_TTML = "application/ttml+xml"
    const val MIME_VTT = "text/vtt"
    const val MIME_SRT = "application/x-subrip"

    /** Only formats Media3 can parse. Anything else is not offered rather than offered-and-broken. */
    fun mimeFor(format: String?): String? = when (format?.lowercase(Locale.ROOT)) {
        "ttml" -> MIME_TTML
        "vtt" -> MIME_VTT
        "srt" -> MIME_SRT
        else -> null
    }

    fun idFor(track: StreamCatalog.SubtitleTrack): String =
        "sub:${track.languageTag}:${if (track.autoGenerated) "auto" else "manual"}"

    fun sources(tracks: List<StreamCatalog.SubtitleTrack>): List<SubtitleSource> =
        tracks.mapNotNull { track ->
            val format = track.formats.firstOrNull { mimeFor(it.format) != null } ?: return@mapNotNull null
            SubtitleSource(
                id = idFor(track),
                label = track.label,
                languageTag = track.languageTag,
                autoGenerated = track.autoGenerated,
                mimeType = mimeFor(format.format)!!,
                url = format.url,
            )
        }
}
